// <autogenerated>
//   This file was generated by T4 code generator ConfigurationCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

// -----------------------------------------------------------------------
//  <copyright file="UserNumberConfiguration.Generated.cs">
//      Copyright (c) 2017 TomNet. All rights reserved.
//  </copyright>
//  <last-editor>TomNet</last-editor>
// -----------------------------------------------------------------------

using System;
using TomNet.Data.Entity;
using Source.Model.DbModels.QRCode;


namespace Source.Core.ModelConfigurations.QRCode
{
    /// <summary>
    /// 实体类-数据表映射 -- Source.Model.DbModels.QRCode.UserNumber
    /// </summary> 
	public partial class UserNumberConfiguration : EntityConfigurationBase<UserNumber, int>
    { 
        /// <summary>
        /// 初始化一个<see cref="UserNumberConfiguration"/>类型的新实例
        /// </summary>
        public UserNumberConfiguration()
        {
            UserNumberConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void UserNumberConfigurationAppend();
    }
}

