// <autogenerated>
//   This file was generated by T4 code generator ConfigurationCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

// -----------------------------------------------------------------------
//  <copyright file="APILogInfoConfiguration.Generated.cs">
//      Copyright (c) 2017 TomNet. All rights reserved.
//  </copyright>
//  <last-editor>TomNet</last-editor>
// -----------------------------------------------------------------------

using System;
using TomNet.Data.Entity;
using Source.Model.DbModels.Base;


namespace Source.Core.ModelConfigurations.Base
{
    /// <summary>
    /// 实体类-数据表映射 -- Source.Model.DbModels.Base.APILogInfo
    /// </summary> 
	public partial class APILogInfoConfiguration : EntityConfigurationBase<APILogInfo, int>
    { 
        /// <summary>
        /// 初始化一个<see cref="APILogInfoConfiguration"/>类型的新实例
        /// </summary>
        public APILogInfoConfiguration()
        {
            APILogInfoConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void APILogInfoConfigurationAppend();
    }
}

